
/****************************************************************************
*                                                                           *
* Trick Simulation Environment Software                                     *
*                                                                           *
* Copyright (c) 1996,1997 LinCom Corporation, Houston, TX                   *
* All rights reserved.                                                      *
*                                                                           *
* Copyrighted by LinCom Corporation and proprietary to it. Any unauthorized *
* use of Trick Software including source code, object code or executables is*
* strictly prohibited and LinCom assumes no liability for such actions or   *
* results thereof.                                                          *
*                                                                           *
* Trick Software has been developed under NASA Government Contracts and     *
* access to it may be granted for Government work by the following contact: *
*                                                                           *
* Contact: Charles Gott, Branch Chief                                       *
*          Simulation and Graphics Branch                                   *
*          Automation, Robotics, & Simulation Division                      *
*          NASA, Johnson Space Center, Houston, TX                          *
*                                                                           *
****************************************************************************/

/*
 * This file was automatically generated by the ICG based on the file:
 * bio/organs/include/organs.h
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 *
 * Auto Code Generator Programmer:
 *    Rob Bailey  Sweet Systems Inc  12/97
 *    Alex Lin    NASA               03/01
 */
#define TRICK_IN_IOSRC

#if __GNUC__ == 2
    #define ADDRESS_OFFSET 1
#else
    #define ADDRESS_OFFSET 0 
#endif

#include <stdlib.h>
#include <stddef.h>
#include "sim_services/include/parameter_types.h"
#include "sim_services/include/exec_proto.h"
#include "trick_utils/trick_adt/include/avl.h"

extern struct avl_table *equiv_attributes ;

#include "bio/organs/include/organs.h"


extern ATTRIBUTES attrREGULA_FALSI[] ;
extern ATTRIBUTES attrTCDevice[] ;
extern ATTRIBUTES attrparams_T[] ;

#ifdef __cplusplus
    extern "C" {
#endif
void init_attrREGULA_FALSI(void) ;
void init_attrTCDevice(void) ;
void init_attrparams_T(void) ;

#ifdef __cplusplus
    }
#endif

void init_attrORGANS(void);

ATTRIBUTES attrORGANS[] = {
{ "Cli", "double", "--", "", "",
  "Concentration in liver",
  3,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Clu", "double", "--", "", "",
  "Concentration in lung",
  3,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Cm", "double", "--", "", "",
  "Concentration in tissue",
  3,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "dC_liver_dt", "double", "--", "", "",
  "Concentration rate in liver",
  3,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "dC_lung_dt", "double", "--", "", "",
  "Concentration rate in lung",
  3,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "dC_tissue_dt", "double", "--", "", "",
  "Concentration rate in medium tissue",
  3,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "params", "params_T", "m", "", "",
  "test",
  2,TRICK_STRUCTURED,sizeof(params_T),0,0,Language_C,0x0,
  0,(char*)attrparams_T, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "rf", "REGULA_FALSI", "--", "", "",
  "Dynamic event params for impact",
  3,TRICK_STRUCTURED,sizeof(REGULA_FALSI),0,0,Language_C,0x0,
  0,(char*)attrREGULA_FALSI, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "connection", "TCDevice", "--", "", "",
  "Socket connection for sending position",
  3,TRICK_STRUCTURED,sizeof(TCDevice),0,0,Language_C,0x0,
  0,(char*)attrTCDevice, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "","","","","","",
  0,0,0,0,0,Language_C,0,0,0,
  0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } };

void init_attrORGANS(void) {


        EQUIV_ATTRIBUTES * equiv;
        ATTRIBUTES* last_non_bf;
        int i = 0;
        static int initialized_1337 ;

        if ( initialized_1337 ) {
                return ;
        }
        initialized_1337 = 1 ;

        last_non_bf = NULL ;
        attrORGANS[i++].offset = offsetof(ORGANS,Cli) ;
        attrORGANS[i++].offset = offsetof(ORGANS,Clu) ;
        attrORGANS[i++].offset = offsetof(ORGANS,Cm) ;
        attrORGANS[i++].offset = offsetof(ORGANS,dC_liver_dt) ;
        attrORGANS[i++].offset = offsetof(ORGANS,dC_lung_dt) ;
        attrORGANS[i++].offset = offsetof(ORGANS,dC_tissue_dt) ;
        attrORGANS[i++].offset = offsetof(ORGANS,params) ;
        attrORGANS[i++].offset = offsetof(ORGANS,rf) ;
        attrORGANS[i++].offset = offsetof(ORGANS,connection) ;

        equiv = (EQUIV_ATTRIBUTES*) malloc(sizeof(EQUIV_ATTRIBUTES));
        equiv->attr = attrORGANS ;
        equiv->base = attrORGANS ;
        avl_insert(equiv_attributes , (void *)equiv) ;

        init_attrparams_T() ;
        init_attrREGULA_FALSI() ;
        init_attrTCDevice() ;
}

