
/****************************************************************************
*                                                                           *
* Trick Simulation Environment Software                                     *
*                                                                           *
* Copyright (c) 1996,1997 LinCom Corporation, Houston, TX                   *
* All rights reserved.                                                      *
*                                                                           *
* Copyrighted by LinCom Corporation and proprietary to it. Any unauthorized *
* use of Trick Software including source code, object code or executables is*
* strictly prohibited and LinCom assumes no liability for such actions or   *
* results thereof.                                                          *
*                                                                           *
* Trick Software has been developed under NASA Government Contracts and     *
* access to it may be granted for Government work by the following contact: *
*                                                                           *
* Contact: Charles Gott, Branch Chief                                       *
*          Simulation and Graphics Branch                                   *
*          Automation, Robotics, & Simulation Division                      *
*          NASA, Johnson Space Center, Houston, TX                          *
*                                                                           *
****************************************************************************/

/*
 * This file was automatically generated by the ICG based on the file:
 * bio/organs/include/organ_params.h
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 *
 * Auto Code Generator Programmer:
 *    Rob Bailey  Sweet Systems Inc  12/97
 *    Alex Lin    NASA               03/01
 */
#define TRICK_IN_IOSRC

#if __GNUC__ == 2
    #define ADDRESS_OFFSET 1
#else
    #define ADDRESS_OFFSET 0 
#endif

#include <stdlib.h>
#include <stddef.h>
#include "sim_services/include/parameter_types.h"
#include "sim_services/include/exec_proto.h"
#include "trick_utils/trick_adt/include/avl.h"

extern struct avl_table *equiv_attributes ;

#include "bio/organs/include/organ_params.h"



#ifdef __cplusplus
    extern "C" {
#endif

#ifdef __cplusplus
    }
#endif

void init_attrparams_T(void);

ATTRIBUTES attrparams_T[] = {
{ "Pli", "double", "--", "", "",
  "liver P param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Plu", "double", "--", "", "",
  "lung P param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Qli", "double", "--", "", "",
  "liver Q param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Qlu", "double", "--", "", "",
  "lung Q param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Qm", "double", "--", "", "",
  "tissue Q param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Vli", "double", "--", "", "",
  "liver V param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Vlu", "double", "--", "", "",
  "lung V param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Vm", "double", "--", "", "",
  "tissue V param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Km_p_450", "double", "--", "", "",
  "Km param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Vmax_p_450", "double", "--", "", "",
  "Vmax p-450 param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Mli", "double", "--", "", "",
  "Mli param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "Mlu", "double", "--", "", "",
  "Mlu param",
  2,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "kinj", "double", "--", "", "",
  "Not Specified",
  3,TRICK_DOUBLE,sizeof(double),0,0,Language_C,0x0,
  0,(char*)0, 0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } ,
{ "","","","","","",
  0,0,0,0,0,Language_C,0,0,0,
  0,{{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0}} } };

void init_attrparams_T(void) {


        EQUIV_ATTRIBUTES * equiv;
        ATTRIBUTES* last_non_bf;
        int i = 0;
        static int initialized_1337 ;

        if ( initialized_1337 ) {
                return ;
        }
        initialized_1337 = 1 ;

        last_non_bf = NULL ;
        attrparams_T[i++].offset = offsetof(params_T,Pli) ;
        attrparams_T[i++].offset = offsetof(params_T,Plu) ;
        attrparams_T[i++].offset = offsetof(params_T,Qli) ;
        attrparams_T[i++].offset = offsetof(params_T,Qlu) ;
        attrparams_T[i++].offset = offsetof(params_T,Qm) ;
        attrparams_T[i++].offset = offsetof(params_T,Vli) ;
        attrparams_T[i++].offset = offsetof(params_T,Vlu) ;
        attrparams_T[i++].offset = offsetof(params_T,Vm) ;
        attrparams_T[i++].offset = offsetof(params_T,Km_p_450) ;
        attrparams_T[i++].offset = offsetof(params_T,Vmax_p_450) ;
        attrparams_T[i++].offset = offsetof(params_T,Mli) ;
        attrparams_T[i++].offset = offsetof(params_T,Mlu) ;
        attrparams_T[i++].offset = offsetof(params_T,kinj) ;

        equiv = (EQUIV_ATTRIBUTES*) malloc(sizeof(EQUIV_ATTRIBUTES));
        equiv->attr = attrparams_T ;
        equiv->base = attrparams_T ;
        avl_insert(equiv_attributes , (void *)equiv) ;

}

